### ISSUE TITLE
Mage spritesheet and animations

### ISSUE THREAD

**Issue by jmontene** [JMakim/game1014-JelloSoft-MageGirl#2]
Find or create a sprite sheet for the heroine. Delimit the sprites and sequences of sprites for the following animations:

-Idle
-Run
-Jump
-Shoot
-Shoot while moving
-Shoot in the air
-Death
-Switch-in
-Switch-out

**Comment by JMakim** [comment]
we should just get a place holder sprite(no animations) for the first playable

**Comment by jmontene** [comment]
Got a placeholder sprite in this commit: 8188a7c03ff45a82503ebac44996887fb805ce76

**Comment by 5N00PD063** [comment]
[Mage-F-01.zip](https://github.com/JMakim/game1014-JelloSoft-MageGirl/files/1129617/Mage-F-01.zip)
![mage-f-01](https://user-images.githubusercontent.com/29510256/27938272-d9766d80-628a-11e7-9e5c-c12bddd1b89d.png)
