### ISSUE TITLE
Mage sound effects

### ISSUE THREAD

**Issue by jmontene** [JMakim/game1014-JelloSoft-MageGirl#32]
- [x] Shooting

- [x] Jump

- [x] Hurt

- [x] Level cleared celebration

- [x] Death

- [x] Level start

**Comment by 5N00PD063** [comment]
[Magic SFX Preview Pack.zip](https://github.com/JMakim/game1014-JelloSoft-MageGirl/files/1129678/Magic.SFX.Preview.Pack.zip)

**Comment by JMakim** [comment]
mage shoot
[Magic Smite.zip](https://github.com/JMakim/game1014-JelloSoft-MageGirl/files/1129729/Magic.Smite.zip)

[https://opengameart.org/content/magic-smite]

**Comment by JMakim** [comment]
jump sfx

(i think jump 8 is better suited)

[8_BIT_[50_SFX]_Jump_Free_Sound_Effects_N1_BY_jalastram.zip](https://github.com/JMakim/game1014-JelloSoft-MageGirl/files/1129751/8_BIT_.50_SFX._Jump_Free_Sound_Effects_N1_BY_jalastram.zip)

[https://opengameart.org/content/8-bit-jump-1]

**Comment by JMakim** [comment]
death and level end

( i do not think the end level is that great but you can decide)


vsgame_0.zip](https://github.com/JMakim/game1014-JelloSoft-MageGirl/files/1129761/vsgame_0.zip)


[https://opengameart.org/content/oldschool-win-and-die-jump-and-run-sounds]

**Comment by 5N00PD063** [comment]
Yeah bro sounds great!

**Comment by 5N00PD063** [comment]
i was thinking use the misc 02 from the zip i uploaded for the hurt sound for now

**Comment by JMakim** [comment]
I separated the ones we need from the file but will still include the whole file

In here is death, hit, level win, and lose sfx

[8-Bit Sound Library.zip](https://github.com/JMakim/game1014-JelloSoft-MageGirl/files/1129793/8-Bit.Sound.Library.zip)


[https://opengameart.org/content/8-bit-sound-effects-library]
