### ISSUE TITLE
Swordfighter sound effects

### ISSUE THREAD

**Issue by jmontene** [JMakim/game1014-JelloSoft-MageGirl#33]
- [x] Slashing

- [x] Jump

- [x] Hurt

- [x] Level cleared celebration

- [x] Death

- [x] Level start

**Comment by JMakim** [comment]
I think most of the SFX got for mage is transferable except slashing

**Comment by JMakim** [comment]
sword sfx

picked best one from pack out

[sword SFX.zip](https://github.com/JMakim/game1014-JelloSoft-MageGirl/files/1129805/sword.SFX.zip)

[https://opengameart.org/content/swishes-sound-pack]
