### ISSUE TITLE
Castle Level Enemy Sprites

### ISSUE THREAD

**Issue by jmontene** [JMakim/game1014-JelloSoft-MageGirl#35]
TBD based on #3

**Comment by 5N00PD063** [comment]
![16x18-2_0](https://user-images.githubusercontent.com/29510256/27929630-ac76c024-6261-11e7-914e-8ce7f226a113.png)

**Comment by 5N00PD063** [comment]
![sprite sheet](https://user-images.githubusercontent.com/29510256/27929692-e89ca168-6261-11e7-9bf9-942aad255647.png)
