### ISSUE TITLE
Coin pickup sound effect

### ISSUE THREAD

**Issue by jmontene** [JMakim/game1014-JelloSoft-MageGirl#37]

**Comment by 5N00PD063** [comment]
[coinPickup.zip](https://github.com/JMakim/game1014-JelloSoft-MageGirl/files/1129622/coinPickup.zip)

**Comment by JMakim** [comment]
[coin_sounds.zip](https://github.com/JMakim/game1014-JelloSoft-MageGirl/files/1129677/coin_sounds.zip)

I think these are better
(gotten from https://opengameart.org/content/10-8bit-coin-sounds)

**Comment by 5N00PD063** [comment]
Yes  I agree I just found those from opengame art and they had some magic sound effects
