### ISSUE TITLE
BGM

### ISSUE THREAD

**Issue by JMakim** [JMakim/game1014-JelloSoft-MageGirl#39]

**Comment by JMakim** [comment]
Here some BGM 

they are Royalty free

[BGM.zip](https://github.com/JMakim/game1014-JelloSoft-MageGirl/files/1129849/BGM.zip)

got from
[http://freemusicarchive.org/genre/Chiptune/]

**Comment by jmontene** [comment]
the third one (neoakushon) is the one I like the most for the main level bgm. Will have to see how it works in game
